name: Build LaTeX

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3
      run: |
        chmod +x build.sh
        ./build.sh --twice --clean